In [1]:
import pandas as pd

In [2]:
pd.set_option('display.max_columns',None)

In [3]:
df = pd.read_csv('train.csv')
df

,ID,LCLAS_NM,MLSFC_NM,POI_ID,POI_NM,BHF_NM,ASSTN_NM,CL_CD,CL_NM,PNU,CTPRVN_NM,SIGNGU_NM,LEGALDONG_NM,LI_NM,LNBR_NO,LEGALDONG_CD,ADSTRD_CD,RDNMADR_CD,RDNMADR_NM,BULD_NO,LC_LO,LC_LA,GID_CD,LAST_CHG_DE,ORIGIN_NM,FILE_NM,BASE_DE
0,KCLANPO22N000000001,장소,관광지,817379,운문호,NaN,NaN,110208,대형호수/저수지,NaN,경상북도,청도군,운문면,대천리,NaN,4782035032,4782035000,NaN,NaN,NaN,128.932090,35.729306,마마295490,20220809,KT,KC_495_LLR_ATRCTN_2022,20220809
1,KCLANPO22N000000002,장소,관광지,5497426,유마사,NaN,NaN,180301,유명사찰,4.680000e+18,전라남도,화순군,사평면,유마리,321,4679041533,4679041500,4.680000e+11,유마로,603,127.171274,35.018297,다라700693,20220809,KT,KC_495_LLR_ATRCTN_2022,20220809
2,KCLANPO22N000000003,장소,관광지,5497607,안정사,NaN,NaN,180301,유명사찰,4.820000e+18,경상남도,통영시,광도면,안정리,1888,4822034027,4822034000,4.820000e+11,안정1길,363,128.395593,34.943969,라라817613,20220809,KT,KC_495_LLR_ATRCTN_2022,20220809
3,KCLANPO22N000000004,장소,관광지,5545868,염불암,NaN,NaN,180301,유명사찰,4.120000e+18,경기도,안양시 만안구,석수동,NaN,241-52,4117110200,4117159000,4.120000e+11,예술공원로245번길,150,126.934391,37.428729,다사499367,20220809,KT,KC_495_LLR_ATRCTN_2022,20220809
4,KCLANPO22N000000005,장소,관광지,332239,귀신사,NaN,NaN,180301,유명사찰,4.520000e+18,전라북도,김제시,금산면,청도리,Jan-82,4521045030,4521045000,4.520000e+11,청도6길,40,127.046958,35.745312,다마590499,20220809,KT,KC_495_LLR_ATRCTN_2022,20220809
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37962,KCLANPO22N000037963,장소,관광지,21621787,새한항업,NaN,NaN,91802,토속/특산물/기념품매장,4.310000e+18,충청북도,청주시 상당구,북문로2가,NaN,116-175,4311110300,4311152500,4.310000e+11,상당로,128,127.490279,36.639754,다바991490,20220809,KT,KC_495_LLR_ATRCTN_2022,20220809
37963,KCLANPO22N000037964,장소,관광지,17484542,합천정원테마파크청와대,NaN,NaN,60507,테마공원/대형놀이공원,4.890000e+18,경상남도,합천군,용주면,가호리,301,4889046037,4889046000,4.890000e+11,합천호수로,777,128.073942,35.554817,라마520289,20220809,KT,KC_495_LLR_ATRCTN_2022,20220809
37964,KCLANPO22N000037965,장소,관광지,17804924,소호해변공원,NaN,NaN,60507,테마공원/대형놀이공원,NaN,전라남도,여수시,소호동,NaN,NaN,4613013100,4613078000,NaN,NaN,NaN,127.651186,34.741940,라라138386,20220809,KT,KC_495_LLR_ATRCTN_2022,20220809
37965,KCLANPO22N000037966,장소,관광지,20019753,렛츠런파크(2023년1월예정),NaN,NaN,60507,테마공원/대형놀이공원,4.720000e+18,경상북도,영천시,금호읍,성천리,산10,4723025023,4723025000,NaN,NaN,NaN,128.873494,35.949442,마마238733,20220809,KT,KC_495_LLR_ATRCTN_2022,20220809
37966,KCLANPO22N000037967,장소,관광지,17411276,금당유원지,NaN,NaN,60508,일반유원지/일반놀이공원,4.570000e+18,전라북도,완주군,운주면,금당리,768,4571038028,4571038000,4.570000e+11,금고당로,92,127.299785,36.070461,다마819859,20220809,KT,KC_495_LLR_ATRCTN_2022,20220809

In [4]:
지역 = '강원도'

In [10]:
df2 = df[df['CTPRVN_NM'].str.startswith(지역)]
df2 = df2.fillna('')
df2.head()

,ID,LCLAS_NM,MLSFC_NM,POI_ID,POI_NM,BHF_NM,ASSTN_NM,CL_CD,CL_NM,PNU,CTPRVN_NM,SIGNGU_NM,LEGALDONG_NM,LI_NM,LNBR_NO,LEGALDONG_CD,ADSTRD_CD,RDNMADR_CD,RDNMADR_NM,BULD_NO,LC_LO,LC_LA,GID_CD,LAST_CHG_DE,ORIGIN_NM,FILE_NM,BASE_DE
11,KCLANPO22N000000012,장소,관광지,16944243,중앙로문화의거리,,,60517,먹거리/패션거리,4210000000000000000.0,강원도,원주시,중앙동,,275,4213010100,4213051500,,,,127.950628,37.349666,라사399279,20220809,KT,KC_495_LLR_ATRCTN_2022,20220809
21,KCLANPO22N000000022,장소,관광지,21086082,대관령옛길,,,60517,먹거리/패션거리,4220000000000000000.0,강원도,강릉시,성산면,어흘리,761,4215031027,4215031000,,,,128.785976,37.701884,마사133677,20220809,KT,KC_495_LLR_ATRCTN_2022,20220809
40,KCLANPO22N000000041,장소,관광지,5851799,인월사,,,180302,지역사찰,4220000000000000000.0,강원도,강릉시,저동,,06월 02일,4215013700,4215066500,422000000000.0,경포로463번안길,12월 21일,128.900632,37.800983,마사233788,20220809,KT,KC_495_LLR_ATRCTN_2022,20220809
41,KCLANPO22N000000042,장소,관광지,6838819,금강선원,,,180302,지역사찰,4280000000000000000.0,강원도,양양군,서면,갈천리,242-9,4283031021,4283031000,428000000000.0,왕생골길,161,128.486023,37.914708,라사866909,20220809,KT,KC_495_LLR_ATRCTN_2022,20220809
43,KCLANPO22N000000044,장소,관광지,6853253,약천사,,,180302,지역사찰,4270000000000000000.0,강원도,홍천군,서석면,어론리,산5-1,4272034027,4272034000,427000000000.0,행치령로,131-20,128.162860,37.730371,라사584702,20220809,KT,KC_495_LLR_ATRCTN_2022,20220809

In [15]:
df2['도로명'] = 지역 +' '+ df2['SIGNGU_NM']+' '+ df2['LEGALDONG_NM']+' '+ df2['LI_NM']+' '+ df2['LNBR_NO']

In [21]:
df2[['POI_NM','LC_LO','LC_LA','도로명']]

         POI_NM       LC_LO      LC_LA                     도로명
11     중앙로문화의거리  127.950628  37.349666        강원도 원주시 중앙동  275
21        대관령옛길  128.785976  37.701884     강원도 강릉시 성산면 어흘리 761
40          인월사  128.900632  37.800983     강원도 강릉시 저동  06월 02일
41         금강선원  128.486023  37.914708    강원도 양양군 서면 갈천리 242-9
43          약천사  128.162860  37.730371    강원도 홍천군 서석면 어론리 산5-1
...         ...         ...        ...                     ...
37928  사천아기동물농장  128.862353  37.846549  강원도 강릉시 사천면 사천진리 305-3
37930  탕곡에코숲하우스  129.226292  37.147970   강원도 삼척시 가곡면 탕곡리 100-1
37939  요술쟁이열손가락  128.916976  37.768088    강원도 강릉시 포남동  1278-44
37941      풍선파티  128.580863  38.199578     강원도 속초시 교동  664-217
37944     색동저고리  127.910182  37.253881   강원도 원주시 흥업면 매지리 647-2

[2658 rows x 4 columns]